name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run GitHub-Profile-3D-Contrib
        uses: yoshi389111/github-profile-3d-contrib@v0.9.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: profile-3d-output
          path: profile-3d-contrib

      - name: Push 3D output to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./profile-3d-contrib
          publish_branch: output
