name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight
  workflow_dispatch:      # Allows manual run button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: GitHub-Profile-3D-Contrib
        uses: yoshi389111/github-profile-3d-contrib@v0.9.1

      - name: Commit and Push changes
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update 3D contributions" || echo "No changes to commit"
          git push
